language: node_js
node_js:
 - '8'
 - '6'
sudo: false
script:
- npm run all
before_install:
  - if [[ `node -v` == v4* ]]; then npm i -g npm@latest-3; fi
  - if [[ `node -v` == v6* ]]; then npm i -g npm@latest-4; fi
  - if [[ `node -v` == v8* ]]; then npm i -g npm@latest-5; fi
deploy:
  provider: npm
  email: git_nikku@nixis.de
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: nikku/karma-browserify
