language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
- stable
sudo: false
script:
- npm test
before_install:
- npm install -g npm@^3.5.2
deploy:
  provider: npm
  email: git_nikku@nixis.de
  api_key:
    secure: J7dPdifl7BhIZIOcN9KosNC3XpwzXTke7OsN8gB9JQS7mqwBMdarNUbQsR6pJoTbX7LPPCIT9pMCi5CPj8txjqSZjqfr4thFVZPdPJAS4guVo0M+dK4JUqk5MMuQksAVMPC12pizunOmmt3l9nWrfz6toHhdqMME1eK1ywBeB2k=
  on:
    tags: true
    all_branches: true
    repo: nikku/karma-browserify
